import { Transaction, AccountInfo, SavingsGoal, EmergencyFundData, RecurringTransaction, ListsConfig, Deposit } from './types';

export const INITIAL_TYPES = ['Opening Balance', 'Income', 'Expense', 'Transfer', 'Adjustment'];

export const INITIAL_CATEGORIES = [
  'Food',
  'Transportation',
  'Education',
  'Organization',
  'Health',
  'Shopping',
  'Entertainment',
  'Other',
];

export const INITIAL_PAYMENT_METHODS = ['Cash', 'QRIS', 'Transfer', 'E-Wallet', 'Virtual Account'];

export const INITIAL_PURPOSES = ['Need', 'Want', 'Investment'];

export const INITIAL_EVENTS = [
  'College',
  'Personal',
  'Travel',
  'Food',
  'Shopping',
  'Family',
  'Organization',
  'Other',
];

export const INITIAL_DEPOSIT_PLATFORMS = [
  'Seabank',
  'Bank Jago',
  'Blu by BCA',
  'BCA',
  'Bank Mandiri',
  'Bibit',
  'Pluang',
  'Aladin',
];

export const INITIAL_SEMESTERS = [
  'Semester 1',
  'Semester 2',
  'Semester 3',
  'Semester 4',
  'Semester 5',
  'Semester 6',
  'Semester 7',
  'Semester 8',
];

export interface MonthOption {
  code: string; // '01' - '12'
  id: string;   // '01' - '12'
  short: string;
  nameId: string;
  nameEn: string;
}

export const ALL_MONTHS: MonthOption[] = [
  { id: '01', code: '01', short: 'Jan', nameId: 'Januari', nameEn: 'January' },
  { id: '02', code: '02', short: 'Feb', nameId: 'Februari', nameEn: 'February' },
  { id: '03', code: '03', short: 'Mar', nameId: 'Maret', nameEn: 'March' },
  { id: '04', code: '04', short: 'Apr', nameId: 'April', nameEn: 'April' },
  { id: '05', code: '05', short: 'May', nameId: 'Mei', nameEn: 'May' },
  { id: '06', code: '06', short: 'Jun', nameId: 'Juni', nameEn: 'June' },
  { id: '07', code: '07', short: 'Jul', nameId: 'Juli', nameEn: 'July' },
  { id: '08', code: '08', short: 'Aug', nameId: 'Agustus', nameEn: 'August' },
  { id: '09', code: '09', short: 'Sep', nameId: 'September', nameEn: 'September' },
  { id: '10', code: '10', short: 'Oct', nameId: 'Oktober', nameEn: 'October' },
  { id: '11', code: '11', short: 'Nov', nameId: 'November', nameEn: 'November' },
  { id: '12', code: '12', short: 'Dec', nameId: 'Desember', nameEn: 'December' },
];

export const INITIAL_DEPOSITS: Deposit[] = [
  {
    id: 'dep-1',
    platform: 'Seabank',
    name: 'Deposito Fleksi 3 Bulan',
    principal: 2000000,
    interestRate: 6.0,
    startDate: '2026-07-01',
    maturityDate: '2026-10-01',
    estimatedInterest: 30247,
    status: 'Active',
    sourceAccount: 'Seabank',
    notes: 'Bunga 6.0% p.a. - Pembayaran bunga saat jatuh tempo',
  },
  {
    id: 'dep-2',
    platform: 'Bank Jago',
    name: 'Kantong Terkunci 1 Bulan',
    principal: 1500000,
    interestRate: 5.0,
    startDate: '2026-08-16',
    maturityDate: '2026-09-16',
    estimatedInterest: 6370,
    status: 'Active',
    sourceAccount: 'Blu',
    notes: 'Segera jatuh tempo dalam 30 hari',
  },
];

export const INITIAL_ACCOUNTS: AccountInfo[] = [
  { name: 'Cash', type: 'Cash', openingBalance: 500000, balance: 500000 },
  { name: 'Blu', type: 'Bank', openingBalance: 3500000, balance: 3500000 },
  { name: 'Blu Pocket', type: 'Bank', openingBalance: 1200000, balance: 1200000 },
  { name: 'Bank Jateng', type: 'Bank', openingBalance: 4000000, balance: 4000000 },
  { name: 'Seabank', type: 'Bank', openingBalance: 5000000, balance: 5000000 },
  { name: 'Shopeepay', type: 'E-Wallet', openingBalance: 350000, balance: 350000 },
  { name: 'Gopay', type: 'E-Wallet', openingBalance: 250000, balance: 250000 },
  { name: 'Dana', type: 'E-Wallet', openingBalance: 150000, balance: 150000 },
];

export const DEFAULT_LISTS_CONFIG: ListsConfig = {
  types: INITIAL_TYPES,
  categories: INITIAL_CATEGORIES,
  accounts: INITIAL_ACCOUNTS,
  paymentMethods: INITIAL_PAYMENT_METHODS,
  purposes: INITIAL_PURPOSES,
  events: INITIAL_EVENTS,
  depositPlatforms: INITIAL_DEPOSIT_PLATFORMS,
  semesters: INITIAL_SEMESTERS,
};

export const INITIAL_BUDGETS: Record<string, number> = {
  Food: 2500000,
  Transportation: 600000,
  Education: 1500000,
  Organization: 300000,
  Health: 400000,
  Shopping: 800000,
  Entertainment: 500000,
  Other: 400000,
};

export const INITIAL_GOALS: SavingsGoal[] = [
  { id: '1', name: 'Emergency fund', targetBalance: 25000000, saved: 14950000, targetDate: '31/12/2026' },
  { id: '2', name: 'Laptop', targetBalance: 15000000, saved: 8500000, targetDate: '30/06/2026' },
  { id: '3', name: 'Staycation', targetBalance: 3000000, saved: 2100000, targetDate: '15/10/2026' },
];

export const INITIAL_EMERGENCY_FUND: EmergencyFundData = {
  targetAmount: 25000000,
  currentAmount: 14950000,
  idealMonths: 6,
  monthlyEssentialExpense: 4166667,
};

export const SAMPLE_TRANSACTIONS: Transaction[] = [
  {
    id: 'tx-1',
    date: '2026-09-01',
    description: 'Monthly Allowance / Freelance Stipend',
    type: 'Income',
    category: 'Other',
    account: 'Seabank',
    paymentMethod: 'Transfer',
    amount: 7500000,
    income: 7500000,
    expense: 0,
    context: 'Income deposit',
    purpose: 'Need',
    event: 'Personal',
    notes: 'Sample starting income',
  },
  {
    id: 'tx-2',
    date: '2026-09-01',
    description: 'Campus Semester Registration & Modules',
    type: 'Expense',
    category: 'Education',
    account: 'Bank Jateng',
    paymentMethod: 'Virtual Account',
    amount: 1200000,
    income: 0,
    expense: 1200000,
    context: 'Academic fee',
    purpose: 'Need',
    event: 'College',
    notes: 'Semester materials',
  },
  {
    id: 'tx-3',
    date: '2026-09-02',
    description: 'Weekly Grocery & Fresh Produce',
    type: 'Expense',
    category: 'Food',
    account: 'Blu',
    paymentMethod: 'QRIS',
    amount: 420000,
    income: 0,
    expense: 420000,
    context: 'Groceries',
    purpose: 'Need',
    event: 'Food, Personal',
    notes: 'Supermarket weekly restock',
  },
  {
    id: 'tx-4',
    date: '2026-09-02',
    description: 'Topup Gopay for Commuter Transport',
    type: 'Transfer',
    category: 'Transportation',
    account: 'Blu',
    toAccount: 'Gopay',
    paymentMethod: 'Transfer',
    amount: 200000,
    income: 0,
    expense: 0,
    context: 'Inter-account transfer',
    purpose: 'Need',
    event: 'Personal',
    notes: 'Transport funds',
  },
  {
    id: 'tx-5',
    date: '2026-09-02',
    description: 'Daily Commute Train & Gojek Ride',
    type: 'Expense',
    category: 'Transportation',
    account: 'Gopay',
    paymentMethod: 'E-Wallet',
    amount: 55000,
    income: 0,
    expense: 55000,
    context: 'Commuting',
    purpose: 'Need',
    event: 'College, Travel',
    notes: 'Roundtrip commute',
  },
  {
    id: 'tx-6',
    date: '2026-09-02',
    description: 'Student Council Annual Dues',
    type: 'Expense',
    category: 'Organization',
    account: 'Shopeepay',
    paymentMethod: 'QRIS',
    amount: 150000,
    income: 0,
    expense: 150000,
    context: 'Campus club',
    purpose: 'Need',
    event: 'Organization',
    notes: 'Activity fund',
  },
  {
    id: 'tx-7',
    date: '2026-09-02',
    description: 'Pharmacy Vitamins & Supplements',
    type: 'Expense',
    category: 'Health',
    account: 'Cash',
    paymentMethod: 'Cash',
    amount: 185000,
    income: 0,
    expense: 185000,
    context: 'Wellness',
    purpose: 'Need',
    event: 'Personal',
    notes: 'Vitamin C and multivitamins',
  },
  {
    id: 'tx-8',
    date: '2026-09-02',
    description: 'Weekend Movie & Dinner with Friends',
    type: 'Expense',
    category: 'Entertainment',
    account: 'Shopeepay',
    paymentMethod: 'QRIS',
    amount: 175000,
    income: 0,
    expense: 175000,
    context: 'Leisure',
    purpose: 'Want',
    event: 'Personal, Food',
    notes: 'Cinema ticket & snacks',
  },
  {
    id: 'tx-9',
    date: '2026-08-28',
    description: 'Study Desk Organizer & Stationery',
    type: 'Expense',
    category: 'Shopping',
    account: 'Shopeepay',
    paymentMethod: 'E-Wallet',
    amount: 240000,
    income: 0,
    expense: 240000,
    context: 'Study supplies',
    purpose: 'Want',
    event: 'College, Shopping',
    notes: 'Online marketplace purchase',
  },
  {
    id: 'tx-10',
    date: '2026-08-15',
    description: 'Tutoring Project Milestone Bonus',
    type: 'Income',
    category: 'Other',
    account: 'Blu',
    paymentMethod: 'Transfer',
    amount: 3000000,
    income: 3000000,
    expense: 0,
    context: 'Side gig',
    purpose: 'Need',
    event: 'Personal',
    notes: 'Design consulting payout',
  }
];

export const SAMPLE_RECURRING_TRANSACTIONS: RecurringTransaction[] = [
  {
    id: 'rec-1',
    description: 'Monthly Allowance & Consulting Retainer',
    type: 'Income',
    category: 'Other',
    account: 'Seabank',
    paymentMethod: 'Transfer',
    amount: 7500000,
    purpose: 'Need',
    event: 'Personal',
    frequency: 'Monthly',
    startDate: '2026-09-01',
    lastGeneratedDate: '2026-09-01',
    status: 'Active',
    notes: 'Auto-deposited on the 1st of each month',
  },
  {
    id: 'rec-2',
    description: 'Boarding House (Kost) Monthly Rental',
    type: 'Expense',
    category: 'Other',
    account: 'Blu',
    paymentMethod: 'Transfer',
    amount: 1500000,
    purpose: 'Need',
    event: 'Personal',
    frequency: 'Monthly',
    startDate: '2026-09-05',
    status: 'Active',
    notes: 'Due on the 5th of each month',
  },
  {
    id: 'rec-3',
    description: 'Mobile Data & WiFi Internet Plan',
    type: 'Expense',
    category: 'Other',
    account: 'Gopay',
    paymentMethod: 'E-Wallet',
    amount: 120000,
    purpose: 'Need',
    event: 'College, Personal',
    frequency: 'Monthly',
    startDate: '2026-09-10',
    status: 'Active',
    notes: 'Telkomsel unlimited monthly package',
  },
  {
    id: 'rec-4',
    description: 'Weekly Meal Prep & Grocery Allowance',
    type: 'Expense',
    category: 'Food',
    account: 'Cash',
    paymentMethod: 'Cash',
    amount: 350000,
    purpose: 'Need',
    event: 'Food',
    frequency: 'Weekly',
    startDate: '2026-09-02',
    lastGeneratedDate: '2026-09-02',
    status: 'Active',
    notes: 'Weekly cash withdrawal for groceries',
  },
  {
    id: 'rec-5',
    description: 'College Student Union Active Dues',
    type: 'Expense',
    category: 'Organization',
    account: 'Shopeepay',
    paymentMethod: 'QRIS',
    amount: 75000,
    purpose: 'Need',
    event: 'College, Organization',
    frequency: 'Monthly',
    startDate: '2026-09-15',
    status: 'Active',
    notes: 'BEM monthly departmental fund',
  },
];
